### ISSUE TITLE
wiki search through inpho API

### ISSUE THREAD

**Issue by colinallen** [inpho/inphosite#155]
Add wiki=id entity search to function just like sep=id does. E.g.,
  inpho.cogs.indiana.edu/entity?wiki=Isaac_Newton&redirect=True 
should go to https://inpho.cogs.indiana.edu/thinker/3635 exactly the same as
  inpho.cogs.indiana.edu/entity?sepi=newton&redirect=True

**Comment by JaimieMurdock** [comment]
Fixed in 7e107c687ac
