### ISSUE TITLE
Instances displaying no data message

### ISSUE THREAD

**Issue by cjbuckner** [inpho/inphosite#157]
All instances are displaying "No Data!" message when clicked on...

**Comment by JaimieMurdock** [comment]
Fixed a separate problem in MySQL, but it seems there's still something up with the fuzzy match

**Comment by JaimieMurdock** [comment]
Fixed! https://inpho.cogs.indiana.edu/idea/1750

Problem originated in a MySQL update that changed a default execution privilege for library-spawned code. 

```WARNING:sqlalchemy.pool.QueuePool.0x...d790:Error closing cursor: (1290, 'The MySQL server is running with the --secure-file-priv option so it cannot execute this statement')```

Fixed with: http://stackoverflow.com/a/40419548
